import { Button } from "@/components/ui/button";
import { ArrowRight, Download, RefreshCw, Home } from "lucide-react";

interface ReportFooterProps {
  onDownload?: () => void;
  onRescan?: () => void;
  onBackHome?: () => void;
}

export const ReportFooter = ({ onDownload, onRescan, onBackHome }: ReportFooterProps) => {
  return (
    <footer className="border-t-2 border-border bg-card">
      <div className="max-w-7xl mx-auto px-6 py-12">
        <div className="text-center space-y-8">
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Button 
              variant="outline" 
              size="lg"
              onClick={onBackHome}
              className="min-w-[200px]"
            >
              <Home className="mr-2 h-5 w-5" />
              Back to Home
            </Button>
            <Button 
              variant="outline" 
              size="lg"
              onClick={onDownload}
              className="min-w-[200px]"
            >
              <Download className="mr-2 h-5 w-5" />
              Download Full Report
            </Button>
            <Button 
              size="lg"
              onClick={onRescan}
              className="min-w-[200px]"
            >
              <RefreshCw className="mr-2 h-5 w-5" />
              Re-scan Website
            </Button>
          </div>

          <div className="pt-6 space-y-2">
            <p className="text-sm font-medium text-muted-foreground">
              Generated by Accessibility & Visual Analyzer
            </p>
            <p className="text-xs text-muted-foreground">
              Version 2.1.0 • Report generated on {new Date().toLocaleDateString()} • 
              Following WCAG 2.1 Level AA guidelines
            </p>
          </div>
        </div>
      </div>
    </footer>
  );
};
